" vim-spellsync: Magically rebuild Vim spell files
" maintainer:    micarmst <https://github.com/micarmst>
" version:       1.0.0

" Copyright (c) 2022 micarmst
"
" MIT License
"
" Permission is hereby granted, free of charge, to any person obtaining a copy
" of this software and associated documentation files (the "Software"), to deal
" in the Software without restriction, including without limitation the rights
" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
" copies of the Software, and to permit persons to whom the Software is
" furnished to do so, subject to the following conditions:
"
" The above copyright notice and this permission notice shall be included in all
" copies or substantial portions of the Software.
"
" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
" SOFTWARE.

let s:gitGenComment = '# Generated by vim-spellsync'

function! spellsync#Run()
  call s:syncSpellDirs()
  call s:syncSpellFiles()
  call s:spellReload()
endfunction

function! s:syncSpellDirs()
  let l:dirs = split(globpath(&runtimepath, 'spell'), '\n')

  for l:dir in l:dirs
    call s:gitSetupUnionMerge(l:dir)
    call s:gitIgnoreSpellFiles(l:dir)
    let l:wordlists = split(globpath(l:dir, '*.add'), '\n')
    for l:wordlist in l:wordlists
      call s:buildSpellFile(l:wordlist)
    endfor
  endfor
endfunction

function! s:syncSpellFiles()
  let l:customSpellFiles = split(&spellfile, ',')
  for l:spellFile in l:customSpellFiles
    let l:dir = fnamemodify(l:spellFile,':h')
    call s:gitSetupUnionMerge(l:dir)
    call s:gitIgnoreSpellFiles(l:dir)
    call s:buildSpellFile(l:spellFile)
  endfor
endfunction

function! s:buildSpellFile(wordlist)
  " Check user has write access to this location
  if !filewritable(a:wordlist)
    return
  endif

  let l:spell_file = a:wordlist . '.spl'

  " Call mkspell if the spell file is out of date
  if getftime(a:wordlist) > getftime(l:spell_file)
    silent! exec 'mkspell! ' . fnameescape(a:wordlist)
  endif
endfunction

function! s:gitSetupUnionMerge(dir)
  if g:spellsync_enable_git_union_merge
    let l:gitattributes = a:dir . '/.gitattributes'
    " Preserve all existing entries, including unreadable files and symlinks.
    if getftype(l:gitattributes) ==# ''
      silent! call writefile([s:gitGenComment, '*.add merge=union'], l:gitattributes)
    endif
  endif
endfunction

function! s:gitIgnoreSpellFiles(dir)
  if g:spellsync_enable_git_ignore
    let l:gitignore = a:dir . '/.gitignore'
    " Preserve all existing entries, including unreadable files and symlinks.
    if getftype(l:gitignore) ==# ''
      silent! call writefile([s:gitGenComment, '*.spl', '*.sug'], l:gitignore)
    endif
  endif
endfunction

function! s:spellReload()
  " :mkspell reloads dictionaries already in use. New runtime additions must
  " also enter the language cache: resetting an option alone does not rescan
  " additions for a language that was already loaded.
  let l:wordlists = []
  for l:lang in split(&l:spelllang, ',')
    " Explicit .spl paths do not use runtime additions; cjk is not a language.
    if l:lang ==# 'cjk' || l:lang =~# '\.spl$'
      continue
    endif
    let l:lang = substitute(l:lang, '_..$', '', '')
    let l:encoding = &encoding ==# 'iso-8859-15' ? 'latin1' : &encoding
    let l:pattern = 'spell/' . l:lang . '.'
    " Match Vim's base-dictionary encoding, including its ASCII fallback.
    if empty(globpath(&runtimepath, l:pattern . l:encoding . '.spl', 1))
      let l:encoding = 'ascii'
      if empty(globpath(&runtimepath, l:pattern . l:encoding . '.spl', 1))
        continue
      endif
    endif
    for l:file in globpath(&runtimepath, l:pattern . l:encoding . '.add.spl', 1, 1)
      call add(l:wordlists, escape(fnamemodify(l:file, ':r'), '\,'))
    endfor
  endfor

  let l:spellfile = &l:spellfile
  let l:spell = &l:spell
  try
    " Load only additions for the current languages, then restore the user's
    " exact setting. This also refreshes explicitly configured spell files.
    if !empty(l:wordlists)
      " Option changes only load dictionaries while spell checking is on.
      silent! noautocmd setlocal spell
      silent! noautocmd let &l:spellfile = join(l:wordlists, ',')
    endif
  finally
    silent! noautocmd let &l:spellfile = l:spellfile
    silent! noautocmd let &l:spell = l:spell
  endtry
endfunction
