" vim-spellsync: Magically rebuild Vim spell files
" maintainer:    micarmst <https://github.com/micarmst>
" version:       1.0.0

" Copyright (c) 2022 micarmst
"
" MIT License
"
" Permission is hereby granted, free of charge, to any person obtaining a copy
" of this software and associated documentation files (the "Software"), to deal
" in the Software without restriction, including without limitation the rights
" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
" copies of the Software, and to permit persons to whom the Software is
" furnished to do so, subject to the following conditions:
"
" The above copyright notice and this permission notice shall be included in all
" copies or substantial portions of the Software.
"
" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
" SOFTWARE.

let s:gitGenComment = '# Generated by vim-spellsync'

function! spellsync#Run()
  call s:syncSpellDirs()
  call s:syncSpellFiles()
  call s:spellReload()
endfunction

function! s:syncSpellDirs()
  " Do not let completion filters hide dictionaries or split names at newlines.
  let l:dirs = globpath(&runtimepath, 'spell', 1, 1)

  for l:dir in l:dirs
    try
      " A discovered directory is a literal name, not another glob pattern.
      " Keep the existing *.add policy (excluding dotfiles), including links.
      let l:names = readdir(l:dir)
      call filter(l:names, 'v:val !~# ''^\.'' && (has(''fname_case'') ? v:val =~# ''\.add$'' : v:val =~? ''\.add$'')')
      let l:wordlists = map(l:names, 'l:dir . ''/'' . v:val')
    catch /^Vim\%((\a\+)\)\=:E/
      call s:warn(l:dir, 'could not read spell directory: ' . v:exception)
      continue
    endtry
    " System runtimes often contain only binaries, with no word lists to sync.
    if empty(l:wordlists)
      continue
    endif
    call s:gitSetupUnionMerge(l:dir)
    call s:gitIgnoreSpellFiles(l:dir)
    for l:wordlist in l:wordlists
      call s:buildSpellFile(l:wordlist)
    endfor
  endfor
endfunction

function! s:spellFiles() abort
  " Match option-list escaping: only an unescaped comma separates paths.
  let l:files = []
  for l:file in split(&spellfile, '\\\@<!,')
    call add(l:files, substitute(l:file, '\\,', ',', 'g'))
  endfor
  return l:files
endfunction

function! s:syncSpellFiles()
  for l:spellFile in s:spellFiles()
    let l:dir = fnamemodify(l:spellFile,':h')
    call s:gitSetupUnionMerge(l:dir)
    call s:gitIgnoreSpellFiles(l:dir)
    call s:buildSpellFile(l:spellFile)
  endfor
endfunction

function! s:buildSpellFile(wordlist) abort
  let l:spell_file = a:wordlist . '.spl'
  try
    " An unused 'spellfile' entry need not exist yet.
    if getftype(a:wordlist) ==# ''
      return
    endif
    " Follow ordinary file symlinks, but never read directories or devices.
    if getftype(resolve(a:wordlist)) !=# 'file'
      call s:warn(a:wordlist, 'source is not a regular file')
      return
    endif
    if !filereadable(a:wordlist)
      call s:warn(a:wordlist, 'source is not readable')
      return
    endif

    let l:output_exists = getftype(l:spell_file) !=# ''
    if l:output_exists && getftype(resolve(l:spell_file)) !=# 'file'
      call s:warn(l:spell_file, 'destination is not a regular file')
      return
    endif
    if l:output_exists && getftime(a:wordlist) <= getftime(l:spell_file)
      return
    endif

    " Updating a file needs write access to the file; creating one needs
    " write access to its directory. Neither requires a writable source.
    if l:output_exists
      if filewritable(l:spell_file) != 1
        call s:warn(l:spell_file, 'destination is not writable')
        return
      endif
    elseif filewritable(fnamemodify(l:spell_file, ':h')) != 2
      call s:warn(l:spell_file, 'destination directory is not writable')
      return
    endif

    " Checks cannot guarantee a successful write (ACLs, races, disk errors).
    " Suppress compiler progress, but catch and report actual failures.
    silent execute 'mkspell! ' . fnameescape(a:wordlist)
  catch /^Vim\%((\a\+)\)\=:E/
    call s:warn(a:wordlist, 'rebuild failed: ' . v:exception)
  endtry
endfunction

function! s:gitSetupUnionMerge(dir)
  if g:spellsync_enable_git_union_merge
    call s:createGitFile(a:dir . '/.gitattributes', ['*.add merge=union'])
  endif
endfunction

function! s:gitIgnoreSpellFiles(dir)
  if g:spellsync_enable_git_ignore
    call s:createGitFile(a:dir . '/.gitignore', ['*.spl', '*.sug'])
  endif
endfunction

function! s:createGitFile(path, rules) abort
  " Preserve all existing entries, including unreadable files and symlinks.
  " Missing directories for unused 'spellfile' entries are also left alone.
  if getftype(a:path) !=# '' || !isdirectory(fnamemodify(a:path, ':h'))
    return
  endif
  if filewritable(fnamemodify(a:path, ':h')) != 2
    call s:warn(a:path, 'Git configuration directory is not writable')
    return
  endif
  try
    if writefile([s:gitGenComment] + a:rules, a:path) != 0
      call s:warn(a:path, 'could not write Git configuration')
    endif
  catch /^Vim\%((\a\+)\)\=:E/
    call s:warn(a:path, 'could not write Git configuration: ' . v:exception)
  endtry
endfunction

function! s:warn(path, message) abort
  echohl WarningMsg
  try
    echomsg 'SpellSync: ' . string(a:path) . ': ' . a:message
  finally
    echohl None
  endtry
endfunction

function! s:setSpellOption(option, value) abort
  let l:isfname = &isfname
  try
    " 'spellfile' validates filenames against 'isfname'. Literal runtime
    " paths may contain other characters, and older editors also validate
    " the backslash in '\,'. Admit only the characters needed for this load.
    if a:option ==# 'spellfile'
      for l:char in split(a:value, '\zs')
        if l:char !~# '^\f$'
          silent noautocmd let &isfname .= ',' . char2nr(l:char)
        endif
      endfor
    endif
    execute 'silent noautocmd let &l:' . a:option . ' = a:value'
  catch /^Vim\%((\a\+)\)\=:E/
    call s:warn(a:option, 'could not refresh spell checking: ' . v:exception)
  finally
    silent noautocmd let &isfname = l:isfname
  endtry
endfunction

function! s:canLoadSpellFile(path) abort
  try
    if getftype(a:path) ==# '' || getftype(resolve(a:path)) ==# 'file'
      return 1
    endif
    call s:warn(a:path, 'refresh deferred: destination is not a regular file')
  catch /^Vim\%((\a\+)\)\=:E/
    call s:warn(a:path, 'refresh deferred: ' . v:exception)
  endtry
  return 0
endfunction

function! s:spellReload()
  " Resetting options makes the editor open binaries itself. Do not let it
  " reopen a rejected device or FIFO; other dictionaries have still synced.
  for l:file in s:spellFiles()
    if !s:canLoadSpellFile(l:file . '.spl')
      return
    endif
  endfor
  " :mkspell reloads dictionaries already in use. New runtime additions must
  " also enter the language cache: resetting an option alone does not rescan
  " additions for a language that was already loaded.
  let l:wordlists = []
  for l:lang in split(&l:spelllang, ',')
    " Explicit .spl paths do not use runtime additions; cjk is not a language.
    if l:lang ==# 'cjk' || l:lang =~# '\.spl$'
      continue
    endif
    let l:lang = substitute(l:lang, '_..$', '', '')
    let l:encoding = &encoding ==# 'iso-8859-15' ? 'latin1' : &encoding
    let l:pattern = 'spell/' . l:lang . '.'
    " Match Vim's base-dictionary encoding, including its ASCII fallback.
    if empty(globpath(&runtimepath, l:pattern . l:encoding . '.spl', 1))
      let l:encoding = 'ascii'
      if empty(globpath(&runtimepath, l:pattern . l:encoding . '.spl', 1))
        continue
      endif
    endif
    for l:file in globpath(&runtimepath, l:pattern . l:encoding . '.add.spl', 1, 1)
      if !s:canLoadSpellFile(l:file)
        return
      endif
      call add(l:wordlists, escape(fnamemodify(l:file, ':r'), '\,'))
    endfor
  endfor

  let l:spellfile = &l:spellfile
  let l:spell = &l:spell
  try
    " Load only additions for the current languages, then restore the user's
    " exact setting. This also refreshes explicitly configured spell files.
    if !empty(l:wordlists)
      " Option changes only load dictionaries while spell checking is on.
      call s:setSpellOption('spell', 1)
      call s:setSpellOption('spellfile', join(l:wordlists, ','))
    endif
  finally
    call s:setSpellOption('spellfile', l:spellfile)
    call s:setSpellOption('spell', l:spell)
  endtry
endfunction
